/*convertir cadena a numeros// M = Float.parseFloat(jt2.getText());//


 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calculadora;

/**
 *
 * @author certificacion8
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    Double  d1=0.0, d2=0.0, d3=0.0;
    String a="";
    int suma=0;
    int res=0;
    int mul=0;
    int div=0;
    int punto=0;
    int ini=0;
    
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton18 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        btnMult = new javax.swing.JButton();
        txtCalculo = new javax.swing.JTextField();
        btnNombre = new javax.swing.JLabel();

        jButton18.setBackground(new java.awt.Color(255, 0, 0));
        jButton18.setText("jButton18");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });

        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });

        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });

        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });

        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });

        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });

        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });

        botonPunto.setText(".");
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });

        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        botonLimpiar.setText("c");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        btnMult.setText("*");
        btnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultActionPerformed(evt);
            }
        });

        txtCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalculoActionPerformed(evt);
            }
        });

        btnNombre.setText("CALCULADORA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnNombre)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btnNombre)
                .addGap(8, 8, 8)
                .addComponent(txtCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton1)
                            .addComponent(boton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnResta))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton4)
                            .addComponent(boton5)
                            .addComponent(boton6)
                            .addComponent(btnDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMult))
                        .addGap(12, 12, 12)
                        .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton7)
                            .addComponent(boton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton0)
                            .addComponent(botonPunto)
                            .addComponent(botonLimpiar))
                        .addGap(13, 13, 13))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        if (ini==0) {
            txtCalculo.setText(txtCalculo.getText() +"2");
        }
        else if (ini==1){
         txtCalculo.setText("2");
         ini=0;
        }
    }//GEN-LAST:event_boton2ActionPerformed

    private void txtCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalculoActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        if (ini==0) {
            txtCalculo.setText(txtCalculo.getText() +"1");
        }
        else if (ini==1){
         txtCalculo.setText("1");
         ini=0;
        }
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        if (ini==0) {
            txtCalculo.setText(txtCalculo.getText() +"3");
        }
        else if (ini==1){
         txtCalculo.setText("3");
         ini=0;
        }
   
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        if (ini==0) {
            txtCalculo.setText(txtCalculo.getText() +"4");
        }
        else if (ini==1){
         txtCalculo.setText("4");
         ini=0;
        }
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        if (ini==0) {
            txtCalculo.setText(txtCalculo.getText() +"5");
        }
        else if (ini==1){
         txtCalculo.setText("5");
         ini=0;
        }
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        if (ini==0) {
            txtCalculo.setText(txtCalculo.getText() +"6");
        }
        else if (ini==1){
         txtCalculo.setText("6");
         ini=0;
        }
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        if (ini==0) {
            txtCalculo.setText(txtCalculo.getText() +"7");
        }
        else if (ini==1){
         txtCalculo.setText("7");
         ini=0;
        }
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        if (ini==0) {
            txtCalculo.setText(txtCalculo.getText() +"8");
        }
        else if (ini==1){
         txtCalculo.setText("8");
         ini=0;
        }
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        if (ini==0) {
            txtCalculo.setText(txtCalculo.getText() +"9");
        }
        else if (ini==1){
         txtCalculo.setText("9");
         ini=0;
        }
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        if (ini==0) {
            txtCalculo.setText(txtCalculo.getText() +"0");
        }
        else if (ini==1){
         txtCalculo.setText("0");
         ini=0;
        }
    }//GEN-LAST:event_boton0ActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        if (punto==0) {
            txtCalculo.setText(txtCalculo.getText() +".");
            punto=1;
        }
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        txtCalculo.setText("0");
        ini=1;
        d1=0.0;
        d2=0.0;
        d3=0.0;
        suma =0; res=0; mul=0; div=0;
        punto=0;
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
       if (suma==0){
           d1 = Double.parseDouble(txtCalculo.getText());
       
            txtCalculo.setText("");
            suma=1;
            punto=0;
       } 
       else if (suma>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1+d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            suma=0;
            punto=0;
            ini=1;
        }
        
       else if (res>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1-d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            res=0;
            ini=1;
            punto=0;
        }
        
       else if (div>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1/d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            div=0;
            ini=1;
            punto=0;
        }
        
       else if (mul>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1*d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            mul=0;
            ini=1;
            punto=0;
        }
        
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        // TODO add your handling code here:
        if (res==0){
           d1 = Double.parseDouble(txtCalculo.getText());
       
            txtCalculo.setText("");
            res=1;
            punto=0;
       } 
        
        else if (suma>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1+d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            suma=0;
            ini=1;
            punto=0;
        }
        
       else if (res>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1-d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            res=0;
            ini=1;
            punto=0;
        }
        
       else if (div>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1/d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            div=0;
            ini=1;
            punto=0;
        }
        
       else if (mul>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1*d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            mul=0;
            ini=1;
            punto=0;
        }
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultActionPerformed
        // TODO add your handling code here:
        punto=0;
        if (mul==0){
           d1 = Double.parseDouble(txtCalculo.getText());
       
            txtCalculo.setText("");
            mul=1;
            punto=0;
       } 
        
        else if (suma>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1+d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            suma=0;
            ini=1;
            punto=0;
        }
        
       else if (res>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1-d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            res=0;
            ini=1;
        }
        
       else if (div>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1/d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            div=0;
            ini=1;
        }
        
       else if (mul>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1*d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            mul=0;
            ini=1;
        }
    }//GEN-LAST:event_btnMultActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        // TODO add your handling code here:
        punto=0;
        if (div==0){
           d1 = Double.parseDouble(txtCalculo.getText());
       
            txtCalculo.setText("");
            div=1;
       } 
        
        else if (suma>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1+d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            suma=0;
            ini=1;
        }
        
       else if (res>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1-d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            res=0;
            ini=1;
        }
        
       else if (div>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1/d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            div=0;
            ini=1;
        }
        
       else if (mul>0){
            d2 = Double.parseDouble(txtCalculo.getText());
            txtCalculo.setText("");
            d3=d1*d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            mul=0;
            ini=1;
        }
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        // TODO add your handling code here:
        d2 = Double.parseDouble(txtCalculo.getText());
        txtCalculo.setText("");
        punto=0;
        ini=1;
        if (suma>0){
            d3=d1+d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            suma=0;
        }
        
        if (res>0){
            d3=d1-d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            res=0;
        }
        
        if (div>0){
            d3=d1/d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            div=0;
        }
        
        if (mul>0){
            d3=d1*d2;
            txtCalculo.setText(String.valueOf(d3));
            d1=0.0;
            d2=0.0;
            mul=0;
        }
    }//GEN-LAST:event_btnIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonPunto;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMult;
    private javax.swing.JLabel btnNombre;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton jButton18;
    private javax.swing.JTextField txtCalculo;
    // End of variables declaration//GEN-END:variables
}
